[tox]
minversion = 4.4.0
envlist =
    clear-coverage
    quality
    py{39,310,311,312}
    compute-coverage
skip_missing_interpreters = True

[testenv]
depends =
    clear-coverage
skip_install =
    coverage: True
deps =
    coverage
commands =
    coverage run --parallel-mode --source=ooolib --branch -m unittest {posargs}

[testenv:clear-coverage]
depends =
commands =
    coverage erase

[testenv:compute-coverage]
depends =
    py{39,310,311,312}
commands =
    coverage combine
    # coverage html -d coverage
    coverage report --include=*/tests/* --fail-under=100 --show-missing
    coverage report --omit=*/tests/* --show-missing  # TODO: --fail-under=100

[testenv:quality]
depends =
extras = quality
# Do not fail on first error, but run all the checks
ignore_errors = True
allowlist_externals =
    mv
commands =
    isort --py 39 --check-only --diff ooolib
    flake8 --format=pylint --show-source ooolib
    pydocstyle ooolib
    # TODO: How exclude these files?
    mv ooolib/__init__.py ooolib/__init__.py.bak
    mv ooolib/tests/test_calc_cell.py ooolib/tests/test_calc_cell.py.bak

    mypy --package ooolib

    mv ooolib/__init__.py.bak ooolib/__init__.py
    mv ooolib/tests/test_calc_cell.py.bak ooolib/tests/test_calc_cell.py
